# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoosuf Muhammad — Software Engineer and Entrepreneur
email: mayooosuf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yoosuf, an experienced full stack Software Engineer and Entrepreneur. Helping people who need Mobile, Wordpres and Rails support.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yoosuf.me" # the base hostname & protocol for your site

#All Social stuff
twitter_username: eyoosuf
github_username:  yoosuf
facebook_username:  yoosuf
linkedin_username:  yoosuf
google_username:  yoosuf
instagram_username:  yoosuf

# Build settings
markdown: kramdown


gems:
  - jekyll-sitemap